name: simonit_dev
description: Personal website of Simon Pham

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
   - family: Iosevka
     fonts:
       - asset: assets/fonts/iosevka-ss08-regular.ttf
       - asset: assets/fonts/iosevka-ss08-italic.ttf
         style: italic
       - asset: assets/fonts/iosevka-ss08-bold.ttf
         weight: 700
       - asset: assets/fonts/iosevka-ss08-bolditalic.ttf
         style: italic
         weight: 700
